#!/usr/bin/env python3

# Form implementation generated from reading ui file 'mainwindow_v2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot
import os


class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setMaximumSize(QtCore.QSize(190, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 171, 246))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LogoLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.LogoLabel.setText("")
        self.LogoLabel.setPixmap(QtGui.QPixmap(os.path.join("ms2analyte", "Qt_Designer_templates", "File_Dialogue",
                                                            "MS2Analyte_logo.png")))
        self.LogoLabel.setObjectName("LogoLabel")
        self.verticalLayout_2.addWidget(self.LogoLabel)
        self.BlanksCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.BlanksCheckBox.setChecked(True)
        self.BlanksCheckBox.setObjectName("BlanksCheckBox")
        self.verticalLayout_2.addWidget(self.BlanksCheckBox)
        self.ReplicatesCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.ReplicatesCheckBox.setChecked(True)
        self.ReplicatesCheckBox.setObjectName("ReplicatesCheckBox")
        self.verticalLayout_2.addWidget(self.ReplicatesCheckBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ReplicateCountLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.ReplicateCountLabel.setEnabled(True)
        self.ReplicateCountLabel.setObjectName("ReplicateCountLabel")
        self.horizontalLayout_6.addWidget(self.ReplicateCountLabel)
        self.ReplicateCountLineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ReplicateCountLineEdit.setEnabled(True)
        self.ReplicateCountLineEdit.setObjectName("ReplicateCountLineEdit")
        self.horizontalLayout_6.addWidget(self.ReplicateCountLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.StandardsCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.StandardsCheckBox.setEnabled(False)
        self.StandardsCheckBox.setObjectName("StandardsCheckBox")
        self.verticalLayout_2.addWidget(self.StandardsCheckBox)
        self.MS2CheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.MS2CheckBox.setChecked(True)
        self.MS2CheckBox.setObjectName("MS2CheckBox")
        self.verticalLayout_2.addWidget(self.MS2CheckBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DDARadioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.DDARadioButton.setEnabled(True)
        self.DDARadioButton.setChecked(False)
        self.DDARadioButton.setObjectName("DDARadioButton")
        self.horizontalLayout_5.addWidget(self.DDARadioButton)
        self.DIARadioButton = QtWidgets.QRadioButton(self.layoutWidget1)
        self.DIARadioButton.setEnabled(True)
        self.DIARadioButton.setChecked(True)
        self.DIARadioButton.setObjectName("DIARadioButton")
        self.horizontalLayout_5.addWidget(self.DIARadioButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.IonMobilityCheckBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.IonMobilityCheckBox.setChecked(True)
        self.IonMobilityCheckBox.setObjectName("IonMobilityCheckBox")
        self.verticalLayout_2.addWidget(self.IonMobilityCheckBox)
        self.horizontalLayout_10.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(10, 260, 551, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 503, 16))
        self.label_7.setObjectName("label_7")
        self.StandardDirectoryCheckBox = QtWidgets.QCheckBox(self.frame)
        self.StandardDirectoryCheckBox.setGeometry(QtCore.QRect(10, 80, 198, 20))
        self.StandardDirectoryCheckBox.setChecked(True)
        self.StandardDirectoryCheckBox.setObjectName("StandardDirectoryCheckBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 551, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ExperimentNameLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.ExperimentNameLabel.setMinimumSize(QtCore.QSize(130, 0))
        self.ExperimentNameLabel.setObjectName("ExperimentNameLabel")
        self.horizontalLayout_8.addWidget(self.ExperimentNameLabel)
        self.ExperimentNameLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ExperimentNameLineEdit.setMinimumSize(QtCore.QSize(407, 21))
        self.ExperimentNameLineEdit.setMaximumSize(QtCore.QSize(407, 21))
        self.ExperimentNameLineEdit.setObjectName("ExperimentNameLineEdit")
        self.horizontalLayout_8.addWidget(self.ExperimentNameLineEdit)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 220, 551, 33))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.OutputDirectoryLabel = QtWidgets.QLabel(self.layoutWidget3)
        self.OutputDirectoryLabel.setEnabled(False)
        self.OutputDirectoryLabel.setMinimumSize(QtCore.QSize(130, 0))
        self.OutputDirectoryLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        self.OutputDirectoryLabel.setObjectName("OutputDirectoryLabel")
        self.horizontalLayout_4.addWidget(self.OutputDirectoryLabel)
        self.OutputLineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.OutputLineEdit.setEnabled(False)
        self.OutputLineEdit.setMinimumSize(QtCore.QSize(315, 21))
        self.OutputLineEdit.setMaximumSize(QtCore.QSize(315, 21))
        self.OutputLineEdit.setObjectName("OutputLineEdit")
        self.horizontalLayout_4.addWidget(self.OutputLineEdit)
        self.OutputPushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.OutputPushButton.setEnabled(False)
        self.OutputPushButton.setMaximumSize(QtCore.QSize(87, 32))
        self.OutputPushButton.setObjectName("OutputPushButton")
        self.horizontalLayout_4.addWidget(self.OutputPushButton)
        self.layoutWidget4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 140, 551, 33))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SampleDirectoryLabel = QtWidgets.QLabel(self.layoutWidget4)
        self.SampleDirectoryLabel.setEnabled(False)
        self.SampleDirectoryLabel.setMinimumSize(QtCore.QSize(130, 0))
        self.SampleDirectoryLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        self.SampleDirectoryLabel.setObjectName("SampleDirectoryLabel")
        self.horizontalLayout_2.addWidget(self.SampleDirectoryLabel)
        self.SampleLineEdit = QtWidgets.QLineEdit(self.layoutWidget4)
        self.SampleLineEdit.setEnabled(False)
        self.SampleLineEdit.setMinimumSize(QtCore.QSize(315, 21))
        self.SampleLineEdit.setMaximumSize(QtCore.QSize(315, 21))
        self.SampleLineEdit.setObjectName("SampleLineEdit")
        self.horizontalLayout_2.addWidget(self.SampleLineEdit)
        self.SamplePushButton = QtWidgets.QPushButton(self.layoutWidget4)
        self.SamplePushButton.setEnabled(False)
        self.SamplePushButton.setMaximumSize(QtCore.QSize(87, 32))
        self.SamplePushButton.setObjectName("SamplePushButton")
        self.horizontalLayout_2.addWidget(self.SamplePushButton)
        self.layoutWidget5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 180, 551, 33))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BlankDirectoryLabel = QtWidgets.QLabel(self.layoutWidget5)
        self.BlankDirectoryLabel.setEnabled(False)
        self.BlankDirectoryLabel.setMinimumSize(QtCore.QSize(130, 0))
        self.BlankDirectoryLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        self.BlankDirectoryLabel.setObjectName("BlankDirectoryLabel")
        self.horizontalLayout_3.addWidget(self.BlankDirectoryLabel)
        self.BlankLineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.BlankLineEdit.setEnabled(False)
        self.BlankLineEdit.setMinimumSize(QtCore.QSize(315, 21))
        self.BlankLineEdit.setMaximumSize(QtCore.QSize(315, 21))
        self.BlankLineEdit.setObjectName("BlankLineEdit")
        self.horizontalLayout_3.addWidget(self.BlankLineEdit)
        self.BlankPushButton = QtWidgets.QPushButton(self.layoutWidget5)
        self.BlankPushButton.setEnabled(False)
        self.BlankPushButton.setMaximumSize(QtCore.QSize(87, 32))
        self.BlankPushButton.setObjectName("BlankPushButton")
        self.horizontalLayout_3.addWidget(self.BlankPushButton)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 40, 551, 33))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ExperimentDirectoryLabel = QtWidgets.QLabel(self.layoutWidget6)
        self.ExperimentDirectoryLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.ExperimentDirectoryLabel.setMaximumSize(QtCore.QSize(130, 16777215))
        self.ExperimentDirectoryLabel.setObjectName("ExperimentDirectoryLabel")
        self.horizontalLayout.addWidget(self.ExperimentDirectoryLabel)
        self.ExperimentLineEdit = QtWidgets.QLineEdit(self.layoutWidget6)
        self.ExperimentLineEdit.setMinimumSize(QtCore.QSize(315, 21))
        self.ExperimentLineEdit.setMaximumSize(QtCore.QSize(315, 21))
        self.ExperimentLineEdit.setObjectName("ExperimentLineEdit")
        self.horizontalLayout.addWidget(self.ExperimentLineEdit)
        self.ExperimentPushButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.ExperimentPushButton.setMaximumSize(QtCore.QSize(87, 32))
        self.ExperimentPushButton.setObjectName("ExperimentPushButton")
        self.horizontalLayout.addWidget(self.ExperimentPushButton)
        self.horizontalLayout_10.addWidget(self.frame)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 10, 761, 52))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InstrumentDetailsLabel = QtWidgets.QLabel(self.layoutWidget7)
        self.InstrumentDetailsLabel.setObjectName("InstrumentDetailsLabel")
        self.verticalLayout_3.addWidget(self.InstrumentDetailsLabel)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ManufacturerLabel = QtWidgets.QLabel(self.layoutWidget7)
        self.ManufacturerLabel.setObjectName("ManufacturerLabel")
        self.horizontalLayout_7.addWidget(self.ManufacturerLabel)
        self.ManufacturerComboBox = QtWidgets.QComboBox(self.layoutWidget7)
        self.ManufacturerComboBox.setObjectName("ManufacturerComboBox")
        self.horizontalLayout_7.addWidget(self.ManufacturerComboBox)
        self.InstrumentLabel = QtWidgets.QLabel(self.layoutWidget7)
        self.InstrumentLabel.setEnabled(True)
        self.InstrumentLabel.setObjectName("InstrumentLabel")
        self.horizontalLayout_7.addWidget(self.InstrumentLabel)
        self.InstrumentComboBox = QtWidgets.QComboBox(self.layoutWidget7)
        self.InstrumentComboBox.setEnabled(True)
        self.InstrumentComboBox.setObjectName("InstrumentComboBox")
        self.horizontalLayout_7.addWidget(self.InstrumentComboBox)
        self.SoftwareLabel = QtWidgets.QLabel(self.layoutWidget7)
        self.SoftwareLabel.setEnabled(True)
        self.SoftwareLabel.setObjectName("SoftwareLabel")
        self.horizontalLayout_7.addWidget(self.SoftwareLabel)
        self.SoftwareComboBox = QtWidgets.QComboBox(self.layoutWidget7)
        self.SoftwareComboBox.setEnabled(True)
        self.SoftwareComboBox.setObjectName("SoftwareComboBox")
        self.horizontalLayout_7.addWidget(self.SoftwareComboBox)
        self.FileTypeLabel = QtWidgets.QLabel(self.layoutWidget7)
        self.FileTypeLabel.setEnabled(True)
        self.FileTypeLabel.setObjectName("FileTypeLabel")
        self.horizontalLayout_7.addWidget(self.FileTypeLabel)
        self.FileTypeComboBox = QtWidgets.QComboBox(self.layoutWidget7)
        self.FileTypeComboBox.setEnabled(True)
        self.FileTypeComboBox.setObjectName("FileTypeComboBox")
        self.horizontalLayout_7.addWidget(self.FileTypeComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 0, 783, 32))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(620, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.SubmitPushButton = QtWidgets.QPushButton(self.layoutWidget8)
        self.SubmitPushButton.setEnabled(True)
        self.SubmitPushButton.setMaximumSize(QtCore.QSize(87, 32))
        self.SubmitPushButton.setObjectName("SubmitPushButton")
        self.horizontalLayout_9.addWidget(self.SubmitPushButton)
        self.verticalLayout_4.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuMS2Analyte = QtWidgets.QMenu(self.menubar)
        self.menuMS2Analyte.setBaseSize(QtCore.QSize(1, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menuMS2Analyte.setFont(font)
        self.menuMS2Analyte.setObjectName("menuMS2Analyte")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_recent.setObjectName("actionOpen_recent")
        self.menuMS2Analyte.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_recent)
        self.menubar.addAction(self.menuMS2Analyte.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.ExperimentPushButton.clicked.connect(self.experiment_browse_slot)
        self.SamplePushButton.clicked.connect(self.sample_browse_slot)
        self.BlankPushButton.clicked.connect(self.blank_browse_slot)
        self.OutputPushButton.clicked.connect(self.output_browse_slot)
        self.ReplicatesCheckBox.stateChanged['int'].connect(self.replicates_check_changed)
        self.StandardDirectoryCheckBox.stateChanged['int'].connect(self.directory_check_changed)
        self.MS2CheckBox.stateChanged['int'].connect(self.ms2_check_changed)
        self.ManufacturerComboBox.activated['QString'].connect(self.manufacturer_dropdown_changed)
        self.SubmitPushButton.clicked.connect(self.submit_slot)
        self.BlanksCheckBox.stateChanged['int'].connect(self.blanks_check_changed)
        self.ReplicateCountLineEdit.textChanged['QString'].connect(self.replicate_count_changed)
        self.DDARadioButton.clicked['bool'].connect(self.ms2_method_changed)
        self.IonMobilityCheckBox.stateChanged['int'].connect(self.ion_mobility_check_changed)
        self.InstrumentComboBox.currentTextChanged['QString'].connect(self.instrument_dropdown_changed)
        self.SoftwareComboBox.currentTextChanged['QString'].connect(self.software_dropdown_changed)
        self.FileTypeComboBox.currentTextChanged['QString'].connect(self.file_type_dropdown_changed)
        self.ExperimentNameLineEdit.textChanged['QString'].connect(self.experiment_name_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MS2Analyte"))
        self.BlanksCheckBox.setText(_translate("MainWindow", "Blanks"))
        self.ReplicatesCheckBox.setText(_translate("MainWindow", "Replicates"))
        self.ReplicateCountLabel.setText(_translate("MainWindow", "Replicate count"))
        self.ReplicateCountLineEdit.setText(_translate("MainWindow", "3"))
        self.StandardsCheckBox.setText(_translate("MainWindow", "Standards"))
        self.MS2CheckBox.setText(_translate("MainWindow", "MS2 data"))
        self.DDARadioButton.setText(_translate("MainWindow", "DDA"))
        self.DIARadioButton.setText(_translate("MainWindow", "DIA"))
        self.IonMobilityCheckBox.setText(_translate("MainWindow", "Ion mobility"))
        self.label_7.setText(_translate("MainWindow", "To select custom directories, uncheck the \'Standard directory structure\' check box"))
        self.StandardDirectoryCheckBox.setText(_translate("MainWindow", "Standard directory structure"))
        self.ExperimentNameLabel.setText(_translate("MainWindow", "Experiment name"))
        self.OutputDirectoryLabel.setText(_translate("MainWindow", "Output directory"))
        self.OutputPushButton.setText(_translate("MainWindow", "Browse"))
        self.SampleDirectoryLabel.setText(_translate("MainWindow", "Samples directory"))
        self.SamplePushButton.setText(_translate("MainWindow", "Browse"))
        self.BlankDirectoryLabel.setText(_translate("MainWindow", "Blanks directory"))
        self.BlankPushButton.setText(_translate("MainWindow", "Browse"))
        self.ExperimentDirectoryLabel.setText(_translate("MainWindow", "Experiment directory"))
        self.ExperimentPushButton.setText(_translate("MainWindow", "Browse"))
        self.InstrumentDetailsLabel.setText(_translate("MainWindow", "Instrument Details"))
        self.ManufacturerLabel.setText(_translate("MainWindow", "Manufacturer"))
        self.InstrumentLabel.setText(_translate("MainWindow", "Instrument"))
        self.SoftwareLabel.setText(_translate("MainWindow", "Software"))
        self.FileTypeLabel.setText(_translate("MainWindow", "File type"))
        self.SubmitPushButton.setText(_translate("MainWindow", "Submit"))
        self.menuMS2Analyte.setTitle(_translate("MainWindow", "MS2Analyte"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionOpen_recent.setText(_translate("MainWindow", "Open recent..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

